server {
    listen 443 ssl;
    server_name letsencrypt.##DOMAIN_NAME##;

    ssl_certificate /etc/volume/certs/letsencrypt.pem
    ssl_certificate_key /etc/volume/private/letsencrypt.key;

    location / {
        root    /etc/volume/data;
        index   index.html;
    }
}

server {
    listen 443 ssl;
    server_name trusted.##DOMAIN_NAME##;

    ssl_certificate /etc/volume/certs/trusted.pem;
    ssl_certificate_key /etc/volume/certs/trusted.key;

    location / {
        root   /etc/volume/data;
        index  trusted.html;
    }
}

sever {
    listen 443 ssl;
    server_name untrusted.##DOMAIN_NAME##;

    ssl_certificate /etc/volume/certs/untrusted.pem;
    ssl_certificate_key /etc/volume/certs/untrusted.key;

    location / {
        root	/etc/volume/data;
        index	untrusted.html;
    }
}

sever {
    listen 443 ssl;
    server_name webapp.##DOMAIN_NAME##;

    ssl_certificate /etc/volume/certs/letsencrypt.pem;
    ssl_certificate_key /etc/volume/certs/letsencrypt.key;

    location / {
        root	/etc/volume/data;
        index	spa.html;
    }
}