logging {

  # Add a Syslog channel, with info severity
  channel my_syslog {
    syslog daemon;
    severity dynamic;

    # Enable all metadata
    print-time yes;
    print-category yes;
    print-severity yes;
  };

  # Set the default destination for all categories
  # >> Uncomment to enable.
  # category default { my_syslog; };

  # Enable query logging by setting this category explicitly
  # >> Uncomment to enable.
  # category queries { my_syslog; };
};

options {
        #dnssec-validation yes;  // this allows forward only zones
        directory "/var/cache/bind";
        listen-on { 127.0.0.1; BIND9_IP; };
        allow-recursion { 127.0.0.1; SUBNET; TUNNEL_CLIENT_SUBNET; };
        allow-transfer { none; };
        allow-update { none; };
        allow-query { 127.0.0.1; SUBNET; TUNNEL_CLIENT_SUBNET; };
        auth-nxdomain no;
};

zone "ZONE_NAME." IN {
        type primary;
        file "/var/lib/bind/forward.resource.db";
        notify no;
};

zone "REVERSE_SUBNET.in-addr.arpa" IN {
        type primary;
        file "/var/lib/bind/reverse.resource.db";
        notify no;
};
